services:

  mongo:
    image: mongo:5.0.3
    ports:
      - 27018:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/ecomm
    ports:
      - 8080:8080

volumes:
  mongo-data:
